name: CLA Check

on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  cla-check:
    runs-on: ubuntu-latest

    steps:
      - name: Get GitHub Username from PR
        id: get_author
        run: |
          echo "AUTHOR=$(jq -r '.pull_request.user.login' "$GITHUB_EVENT_PATH")" >> $GITHUB_ENV

      - name: Check if User Has Signed CLA
        id: check_cla
        run: |
          RESPONSE=$(curl -s -X POST "http://localhost:5000/api/check-cla" -H "Content-Type: application/json" -d "{\"username\": \"${{ env.AUTHOR }}\"}")
          SIGNED=$(echo $RESPONSE | jq -r '.signed')

          if [[ "$SIGNED" == "true" ]]; then
            echo "✅ User ${{ env.AUTHOR }} has signed the CLA."
          else
            echo "❌ User ${{ env.AUTHOR }} has NOT signed the CLA."
            echo "::error::Contributor has not signed the CLA."
            exit 1
          fi

      - name: Comment on PR If CLA Not Signed
        if: failure()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const author = process.env.AUTHOR;
            const issue_number = context.payload.pull_request.number;
            const repo = context.repo.repo;
            const owner = context.repo.owner;

            const message = `@${author}, you need to sign the CLA before we can merge your PR.\n\n🔗 Please sign the CLA here: [Sign CLA](http://localhost:5000/CLAAuth)\n\nOnce you've signed, re-run the checks by pushing a new commit or closing and reopening the PR.`;

            github.rest.issues.createComment({
              owner,
              repo,
              issue_number,
              body: message
            });